tests <- tibble::tibble(
  Test = c(
    "Beck Anxiety Inventory",
    "Beck Depression Inventory",
    "Boston Naming Test",
    "Brief Visuospatial Memory Test - Revised",
    "California Verbal Learning Test - II",
    "Conners' Adult ADHD Rating Scales - Self Report: Long Version",
    "Conners' Continuous Performance Test - 3rd Edition",
    "Controlled Oral Word Association Test",
    "Minnesota Multiphasic Personality Inventory - 2 Restructured Form",
    "Rey-Osterrieth Complex Figure Test",
    "Stroop - Word Naming",
    "Stroop - Color Naming",
    "Stroop - Colored Word Naming",
    "Test of Premorbid Function",
    "Trailmaking Test A",
    "Trailmaking Test B",
    "Wechsler Adult Intelligence Scale - 4th Edition",
    "Wechsler Memory Scale - 4th Edition",
    "Wisconsin Card Sorting Test"
  ),
  Abbreviation = c(
    "bai",
    "bdi_ii",
    "bnt",
    "bvmt_r",
    "cvlt_ii",
    "caars_s_l",
    "cpt_3",
    "fas_animals",
    "mmpi_2_rf",
    "rocft",
    "stroop_word",
    "stroop_color",
    "stroop_color_word",
    "topf",
    "trailmaking_a",
    "trailmaking_b",
    "wais_iv",
    "wms_iv",
    "wcst"
  )
)

tests <- tests |>
  dplyr::mutate(
    subtest = dplyr::case_when(
      Abbreviation == "wais_iv" ~ "Similarities",
      TRUE ~ NA_character_
    ),
    subtest2 = dplyr::case_when(
      Abbreviation == "wais_iv" ~ "Vocabulary",
      TRUE ~ NA_character_
    ),
    subtest3 = dplyr::case_when(
      Abbreviation == "wais_iv" ~ "Information",
      TRUE ~ NA_character_
    ),
    subtest4 = dplyr::case_when(
      Abbreviation == "wais_iv" ~ "Digit Span",
      TRUE ~ NA_character_
    ),
    subtest5 = dplyr::case_when(
      Abbreviation == "wais_iv" ~ "Arithmetic",
      TRUE ~ NA_character_
    ),
    subtest6 = dplyr::case_when(
      Abbreviation == "wais_iv" ~ "Block Design",
      TRUE ~ NA_character_
    ),
    subtest7 = dplyr::case_when(
      Abbreviation == "wais_iv" ~ "Matrix Reasoning",
      TRUE ~ NA_character_
    ),
    subtest8 = dplyr::case_when(
      Abbreviation == "wais_iv" ~ "Visual Puzzles",
      TRUE ~ NA_character_
    ),
    subtest9 = dplyr::case_when(
      Abbreviation == "wais_iv" ~ "Coding",
      TRUE ~ NA_character_
    ),
    subtest10 = dplyr::case_when(
      Abbreviation == "wais_iv" ~ "Symbol Search",
      TRUE ~ NA_character_
    )
  )

# shiny app below this
library(shiny)

shinyApp(
  ui = fluidPage(
    title = "Template Creation for Neuropsychology Patient Reports",

    sidebarLayout(
      sidebarPanel(
        textInput("patient_name", "Patient's Name"),
        textInput("dob", "Patient's Date of Birth"),
        textInput("city", "City patient resides in"),
        textInput("state", "State patient resides in"),
        textInput("interview_date", "Interview Date (e.g., MM/DD/YYYY)"),
        textInput("testing_date", "Testing Date (e.g., MM/DD/YYYY)"),
        textInput("examiner", "Examiner's Name"),
        textInput("examiner_title", "Examiner's Title"),
        textInput("examiner_license", "Examiner's License/Fellow Number"),
        selectInput("examiner2_tf", "Is there a second examiner", choices = c(TRUE, FALSE)),
        textInput("examiner2", "Second Examiner's Name"),
        textInput("examiner2_title", "Second Examiner's Title"),
        textInput("examiner2_license", "Second Examiner's License/Fellow Number"),
        selectInput("examiner3_tf", "Is there a third examiner", choices = c(TRUE, FALSE)),
        textInput("examiner3", "Third Examiner's Name"),
        textInput("examiner3_title", "Third Examiner's Title"),
        textInput("examiner3_license", "Third Examiner's License/Fellow Number"),
        selectInput("mr_ms", "Name prefix", choices = c("Mr.", "Ms", "Mrs.", "Dr.")),
        selectInput("male_female", "Male/Female/Non-binary", choices = c("male", "female", "non-binary")),
        selectInput("his_her_their", "His/Her/Their", choices = c("his", "her", "their")),
        selectInput("he_she_they", "He/She/They", choices = c("he", "she", "they")),
        textInput("patient_age", "Patient's Age"),
        selectInput("handed", "Right or left-handed", choices = c("right", "left")),
        selectInput("marital_status", "Patient's marital status", choices = c("single", "married", "widowed", "divorced", "separated")),
        textInput("race_ethnicity", "Patient's Race/Ethnicity"),
        selectInput("bilingual", "Is the patient bilingual?", choices = c(TRUE, FALSE)),
        textInput("years_of_ed", "Years of Education"),
        selectInput("referred", "Is the patient referred by a doctor?", choices = c(TRUE, FALSE)),
        textInput("referring_dr", "Referring Doctor's Name (e.g., Dr. Sam I Am)"),
        selectInput("past_diagnosis_tf", "The patient have a past diagnosis?", choices = c(TRUE, FALSE)),
        textInput("past_diagnosis", "What is/are the patient's past diagnosis/diagnoses?"),
        textInput("past_dr_diagnosing", "Past doctor to diagnose previous diagnosis/diagnoses (e.g., pediatrician)"),
        textInput("age_of_diagnosis", "At what age was the patient diagnosed (e.g., 8-years old)."),
        textInput("time_of_symptom_concern", "When were the symptoms becoming problematic (i.e., kindergarten)"),
        textInput("major_medical_issues", "List all the major medical issues (e.g., chronic pain, arthiritis, asthma)"),
        textInput("diagnosis_symptoms", "List all the symptoms related to being evaluated."),
        textInput("current_medications", "List medications currently taking. If none write 'not currently taking medication.'"),
        textInput("past_medications", "List medication(s) previously taken."),
        
        # test scores
        textInput("raw_topf", "TOPF score - Raw"),
        textInput("standard_topf", "TOPF score - Standard"),
        textInput("percentile_topf", "TOPF score - Percentile"),
        textInput("score_cvlt_ii_fc", "CVLT-II FC Score"),
        textInput("total_cvlt_ii_fc", "CVLT-II FC Total Score"),
        textInput("score_rds", "RDS Score"),
        textInput("tomm_trial_1", "TOMM Trial 1"),
        textInput("tomm_trial_2", "TOMM Trial 2"),
        textInput("raw_similarities", "Raw Similarities Score"),
        textInput("acss_similarities", "ACSS Similarities Score"),
        textInput("percentile_similarities", "Percentile Similarities Score"),
        textInput("raw_information", "Raw Information Score"),
        textInput("acss_information", "ACSS Information Score"),
        textInput("percentile_information", "Percentile Information Score"),
        textInput("raw_vocab", "Raw Vocab Score"),
        textInput("acss_vocab", "ACSS Vocab Score"),
        textInput("percentile_vocab", "Percentile Vocab Score"),
        textInput("raw_block_design", "Raw Block Design Score"),
        textInput("acss_block_design", "ACSS Block Design Score"),
        textInput("percentile_block_design", "Percentile Block Design Score"),
        textInput("raw_matrix_reason", "Raw Matrix Reasoning Score"),
        textInput("acss_matrix_reason", "ACSS Matrix Reasoning Score"),
        textInput("percentile_matrix_reason", "Percentile Matrix Reasoning Score"),
        textInput("raw_visual_puzzle", "Raw Visual Puzzle Score"),
        textInput("acss_visual_puzzle", "ACSS Visual Puzzle Score"),
        textInput("percentile_visual_puzzle", "Percentile Visual Puzzle Score"),
        textInput("raw_digit_span", "Raw Digit Span Score"),
        textInput("acss_digit_span", "ACSS Digit Span Score"),
        textInput("percentile_digit_span", "Percentile Digit Span Score"),
        textInput("raw_arithmetic", "Raw Arithmetic Score"),
        textInput("acss_arithmetic", "ACSS Arithmetic Score"),
        textInput("percentile_arithmetic", "Percentile Arithmetic Score"),
        textInput("raw_symbol_s", "Raw Symbol S Score"),
        textInput("acss_symbol_s", "ACSS Symbol S Score"),
        textInput("percentile_symbol_s", "Percentile Symbol S Score"),
        textInput("raw_coding", "Raw Coding Score"),
        textInput("acss_coding", "ACSS Coding Score"),
        textInput("percentile_coding", "Percentile Coding Score"),
        textInput("raw_wais_vcl", "Raw WAIS-IV VCL"),
        textInput("standard_wais_vcl", "Standard WAIS-IV VCL"),
        textInput("percentile_wais_vcl", "Percentile WAIS-IV VCL"),
        textInput("raw_wais_pri", "Raw WAIS-IV PRI"),
        textInput("standard_wais_pri", "Standard WAIS-IV PRI"),
        textInput("percentile_wais_pri", "Percentile WAIS-IV PRI"),
        textInput("raw_wais_gai", "Raw WAIS-IV GAI"),
        textInput("standard_wais_gai", "Standard WAIS-IV GAI"),
        textInput("percentile_wais_gai", "Percentile WAIS-IV GAI"),
        textInput("raw_wais_wmi", "Raw WAIS-IV WMI"),
        textInput("standard_wais_wmi", "Standard WAIS-IV WMI"),
        textInput("percentile_wais_wmi", "Percentile WAIS-IV WMI"),
        textInput("raw_wais_psi", "Raw WAIS-IV PSI"),
        textInput("standard_wais_psi", "Standard WAIS-IV PSI"),
        textInput("percentile_wais_psi", "Percentile WAIS-IV PSI"),
        textInput("raw_wais_fsiq", "Raw WAIS-IV FSIQ"),
        textInput("standard_wais_fsiq", "Standard WAIS-IV FSIQ"),
        textInput("percentile_fsiq", "Percentile WAIS-IV FSIQ"),
        textInput("raw_wais_ds", "Raw WAIS-IV DS"),
        textInput("acss_wais_ds", "Standard WAIS-IV DS"),
        textInput("percentile_wais_ds", "Percentile WAIS-IV DS"),
        textInput("raw_ds_fwd", "Raw DS Fwd"),
        textInput("acss_ds_fwd", "Standard DS Fwd"),
        textInput("percentile_ds_fwd", "Percentile DS Fwd"),
        textInput("raw_ds_bwd", "Raw DS Bwd"),
        textInput("acss_ds_bwd", "Standard DS Bwd"),
        textInput("percentile_ds_bwd", "Percentile DS Bwd"),
        textInput("raw_ds_seq", "Raw DS Seq"),
        textInput("acss_ds_seq", "Standard DS Seq"),
        textInput("percentile_ds_seq", "Percentile DS Seq"),
        textInput("longest_fwd", "Longest Fwd"),
        textInput("longest_bwd", "Longest Bwd"),
        textInput("longest_seq", "Longest Seq"),
        textInput("t_cpt3_d", "t-score Conner's CPT-3 d"),
        textInput("rating_cpt3_d", "Rating (e.g., Average, Low, etc.) Conners CPT-3 d"),
        textInput("t_cpt3_omissions", "t-score Conners CPT-3 Omissions"),
        textInput("rating_cpt3_omissions", "Rating (e.g., Average) Conners CPT-3 Omissions"),
        textInput("t_cpt3_commissions", "t-score Conners CPT-3 Commissions"),
        textInput("rating_cpt3_commissions", "Rating (e.g., Average) Conners CPT-3 Commissions"),
        textInput("t_cpt3_perseverations", "t-score Conners CPT-3 Perseverations"),
        textInput("rating_cpt3_perseverations", "Rating (e.g., Average) Conners CPT-3 Perseverations"),
        textInput("raw_wais_ss", "Raw WAIS-IV SS"),
        textInput("acss_wais_ss", "Standard WAIS-IV SS"),
        textInput("percentile_wais_ss", "Percentile WAIS-IV SS"),
        textInput("raw_wais_co", "Raw WAIS-IV CO"),
        textInput("acss_wais_co", "Standard WAIS-IV CO"),
        textInput("percentile_wais_co", "Percentile WAIS-IV CO"),
        textInput("raw_stroop_word", "Raw Stroop (Word)"),
        textInput("t_stroop_word", "t-score Stroop (Word)"),
        textInput("percentile_stroop_word", "Percentile Stroop (Word)"),
        textInput("error_stroop_word", "Error Stroop (Word)"),
        textInput("raw_stroop_color", "Raw Stroop (Color)"),
        textInput("t_stroop_color", "t-score Stroop (Color)"),
        textInput("percentile_stroop_color", "Percentile Stroop (Color)"),
        textInput("error_stroop_color", "Error Stroop (Color)"),
        textInput("raw_trails_a", "Raw Trails A"),
        textInput("z_trails_a", "z-score Trails A"),
        textInput("percentile_trails_a", "Percentile Trails A"),
        textInput("error_trails_a", "Error Trails A"),
        textInput("raw_hrt", "Raw HRT"),
        textInput("t_hrt", "t-score HRT"),
        selectInput("rating_hrt", "Rating HRT", choices = c("Atypically Low", "Low", "Average", "Fast", "Atypically Fast")),
        textInput("raw_hrt_sd", "Raw HRT SD"),
        textInput("t_hrt_sd", "t-score HRT SD"),
        selectInput("rating_hrt_sd", "Rating HRT SD", choices = c("Atypically Low", "Low", "Average", "Fast", "Atypically Fast")),
        textInput("raw_variability", "Raw Variability"),
        textInput("t_variability", "t-score Variability"),
        selectInput("rating_variability", "Rating Variability", choices = c("Atypically Low", "Low", "Average", "Fast", "Atypically Fast")),
        textInput("raw_hrt_block_change", "Raw HRT Block Change"),
        textInput("t_hrt_block_change", "t-score HRT Block Change"),
        selectInput("rating_hrt_block_change", "Rating HRT Block Change", c("Atypically Low", "Low", "Average", "Fast", "Atypically Fast")),
        textInput("raw_hrt_isi_change", "Raw HRT ISI Change"),
        textInput("t_hrt_isi_change", "t-score HRT ISI Change"),
        selectInput("rating_hrt_isi_change", "Rating HRT ISI Change", c("Atypically Low", "Low", "Average", "Fast", "Atypically Fast")),
        textInput("raw_wcst_categ", "Raw WCST-64 Categories"),
        textInput("percentile_wcst_categ", "Percentile WCST-64 Categories"),
        textInput("raw_wcst_p_errors", "Raw WCST P Errors"),
        textInput("percentile_wcst_p_errors", "Percentile WCST P Errors"),
        textInput("raw_wcst_clr", "Raw WCST CLR"),
        textInput("percentile_wcst_clr", "Percentile WCST CLR"),
        textInput("raw_wcst_fms", "Raw WCST FMS"),
        textInput("percentile_wcst_fms", "Percentile WCST FMS"),
        textInput("raw_wais_si", "Raw WAIS-IV SI"),
        textInput("acss_wais_si", "Standard WAIS-IV SI"),
        textInput("percentile_wais_si", "Percentile WAIS-IV SI"),
        textInput("raw_wais_mr", "Raw WAIS-IV MR"),
        textInput("acss_wais_mr", "Standard WAIS-IV MR"),
        textInput("percentile_wais_mr", "Percentile WAIS-IV MR"),
        textInput("raw_trails_b", "Raw Trails B"),
        textInput("z_trails_b", "z-score Trails B"),
        textInput("percentile_trails_b", "Percentile Trails B"),
        textInput("raw_stroop_cw", "Raw Stroop (CW)"),
        textInput("t_stroop_cw", "t-score Stroop (CW)"),
        textInput("percentile_stroop_cw", "Percentile Stroop (CW)"),
        textInput("raw_fas", "Raw FAS"),
        textInput("z_fas", "z-score FAS"),
        textInput("percentile_fas", "Percentile FAS"),
        textInput("raw_fas_lang", "Raw FAS Lang"),
        textInput("z_fas_lang", "z-score FAS Lang"),
        textInput("percentile_fas_lang", "Percentile FAS Lang"),
        textInput("raw_animals", "Raw Animals"),
        textInput("z_animals", "z-score Animals"),
        textInput("percentile_animals", "Percentile Animals"),
        textInput("raw_wais_vc", "Raw WAIS-IV VC"),
        textInput("z_wais_vc", "z-score WAIS-IV VC"),
        textInput("percentile_wais_vc", "Percentile WAIS-IV VC"),
        textInput("raw_wais_bd", "Raw WAIS-IV BD"),
        textInput("acss_wais_bd", "Standard WAIS-IV BD"),
        textInput("percentile_wais_bd", "Percentile WAIS-IV BD"),
        textInput("raw_wais_vp", "Raw WAIS-IV VP"),
        textInput("acss_wais_vp", "Standard WAIS-IV VP"),
        textInput("percentile_wais_vp", "Percentile WAIS-IV VP"),
        textInput("raw_rcft_copy", "Raw RCFT Copy"),
        textInput("acss_rcft_copy", "Standard RCFT Copy"),
        textInput("percentile_rcft_copy", "Percentile RCFT Copy"),
        textInput("raw_cvlt_3", "Raw CVLT-3"),
        textInput("acss_cvlt_3", "Standard CVLT-3"),
        textInput("percentile_cvlt_3", "Percentile CVLT-3"),
        textInput("raw_trials", "Raw Trials 1-5"),
        textInput("t_trials", "t-score Trials 1-5"),
        textInput("percentile_trials", "Percentile Trials 1-5"),
        textInput("raw_list_b", "Raw List B"),
        textInput("acss_list_b", "Standard List B"),
        textInput("percentile_list_b", "Percentile List B"),
        textInput("raw_sd_free", "Raw SD Free"),
        textInput("acss_sd_free", "Standard SD Free"),
        textInput("percentile_sd_free", "Percentile SD Free"),
        textInput("raw_sd_cued", "Raw SD Cued"),
        textInput("acss_sd_cued", "Standard SD Cued"),
        textInput("percentile_sd_cued", "Percentile SD Cued"),
        textInput("raw_ld_free", "Raw LD Free"),
        textInput("acss_ld_free", "Standard LD Free"),
        textInput("percentile_ld_free", "Percentile LD Free"),
        textInput("raw_ld_cued", "Raw LD Cued"),
        textInput("acss_ld_cued", "Standard LD Cued"),
        textInput("percentile_ld_cued", "Percentile LD Cued"),
        textInput("raw_repetitions", "Raw Repetitions"),
        textInput("acss_repetitions", "Standard Repetitions"),
        textInput("percentile_repetitions", "Percentile Repetitions"),
        textInput("raw_intrusions", "Raw Intrusions"),
        textInput("acss_intrusions", "Standard Intrusions"),
        textInput("percentile_intrusions", "Percentile Intrusions"),
        textInput("raw_recog_hits", "Raw Recog Hits"),
        textInput("acss_recog_hits", "Standard Recog Hits"),
        textInput("percentile_recog_hits", "Percentile Recog Hits"),
        textInput("raw_false_positives", "Raw False Positives"),
        textInput("acss_false_positives", "Standard False Positives"),
        textInput("percentile_false_positives", "Percentile False Positives"),
        textInput("raw_ld_recog_accuracy", "Raw LD Recog Accuracy"),
        textInput("acss_ld_recog_accuracy", "Standard LD Recog Accuracy"),
        textInput("percentile_ld_recog_accuracy", "Percentile LD Recog Accuracy"),
        textInput("raw_wms_iv", "Raw WMS-IV"),
        textInput("acss_wms_iv", "Standard WMS-IV"),
        textInput("percentile_wms_iv", "Percentile WMS-IV"),
        textInput("raw_lm_i", "Raw LM I"),
        textInput("acss_lm_i", "Standard LM I"),
        textInput("percentile_lm_i", "Percentile LM I"),
        textInput("raw_lm_ii", "Raw LM II"),
        textInput("acss_lm_ii", "Standard LM II"),
        textInput("percentile_lm_ii", "Percentile LM II"),
        textInput("raw_recognition", "Raw Recognition"),
        textInput("acss_recognition", "Standard Recognition"),
        textInput("percentile_recognition", "Percentile Recognition"),
        textInput("raw_rcft_3", "Raw RCFT 3\" Delay"),
        textInput("t_rcft_3", "t-score RCFT 3\" Delay"),
        textInput("percentile_rcft_3", "Percentile RCFT 3\" Delay"),
        textInput("raw_rcft_30", "Raw RCFT 30\" Delay"),
        textInput("t_rcft_30", "t-score RCFT 30\" Delay"),
        textInput("percentile_rcft_30", "Percentile RCFT 30\" Delay"),
        textInput("raw_rcft_total_recog", "Raw RCFT Total Recog"),
        textInput("t_rcft_total_recog", "t-score RCFT Total Recog"),
        textInput("percentile_rcft_total_recog", "Percentile RCFT Total Recog"),
        textInput("score_bdi_ii", "BDI-II Patient Score"),
        textInput("score_bai", "BAI Patient Score"),
        textInput("t_inattention", "t-score Inattention/Memory Problems"),
        textInput("t_hyperactivity", "t-score Hyperactivity/Restlessness"),
        textInput("t_impulsivity", "t-score Impulsivity/Emotional Lability"),
        textInput("t_self_concept", "t-score Problems with Self-Concept"),
        textInput("t_dsm_inattentive", "t-score DSM-IV Inattentive Symptoms"),
        textInput("t_dsm_hyperactive", "t-score DSM-IV Hyperactive-Impulsive Symptoms"),
        textInput("t_dsm_adhd_total", "t-score DSM-IV ADHD Symptoms Total"),
        textInput("t_adhd_index", "t-score ADHD Index"),
        selectInput("level_depression", "Level of Depression Severity", choices = c("minimal", "mild", "moderate", "severe")),
        selectInput("level_anxiety", "Level of Anxiety Severity", choices = c("minimal", "mild", "moderate", "severe")),

        textAreaInput("beginning_symptoms", "Patient's beginning of the symptoms", height = "200px"),
        textAreaInput("hs_college_symptoms", "Patient's symptoms during high school and college", height = "200px"),
        textAreaInput("occupational_symptoms", "Patient's symptoms during occupation", height = "200px"),
        textAreaInput("current_mood", "Patient's current mood", height = "200px"),
        textAreaInput("current_sleep", "Patient's current sleep patterns", height = "200px"),
        textAreaInput("motor_sensory_functioning", "Patient's motor and sensorying functioning", height = "200px"),
        textAreaInput("current_functioning", "Patient's current functioning (Starts Current Functioning:)", height = "200px"),
        textAreaInput("medical_history", "Patient's medical history (Starts Medical History:)", height = "200px"),
        textAreaInput("family_history", "Patient's family history of symptoms", height = "200px"),
        textAreaInput("psychiatric_history", "Patient's psychiatric history (Starts Psychiatric History and Substance Use)", height = "200px"),
        textAreaInput("substance_use_history", "Patient's substance use history.", height = "200px"),
        textAreaInput("developmental_ed_social_occupation", "Patient's developmental, educational, social, and occupational history (Starts Developmental, Educational, Social, and Occupational History)", height = "200px"),
        textAreaInput("behavioral_observations", "Patient's behavioral observations", height = "200px"),
        checkboxGroupInput("administered_tests", "What tests were Administered (Check All)", choices = tests$Test),
        textAreaInput("intellectual_functioning_results", "Intellectual Functioning Results", height = "200px"),
        textAreaInput("attention_concentration_results", "Attention/Concentration Results", height = "200px"),
        textAreaInput("processing_speed_results", "Processing Speed Results", height = "200px"),
        textAreaInput("executive_function_results", "Executive Functioning Results", height = "200px"),
        textAreaInput("language_skill_results", "Language Skills Results", height = "200px"),
        textAreaInput("visual_spatial_results", "Visual-Spatial Results", height = "200px"),
        textAreaInput("memory_results", "Memory Results", height = "200px"),
        textAreaInput("mood_personality_results", "Mood/Personality Results", height = "200px"),
        textAreaInput("summary_impressions", "Summary & Impressions", height = "200px"),
        selectInput("academic_accommodations", "The patient need academic accommodations.", choices = c(TRUE, FALSE)),
  
        # selectInput("report_type", "Word doc = .docx; pdf = .pdf; web page = .html", choices = c(".docx", ".pdf", ".html")),
        downloadButton("report", "Generate report"),
        width = 4
    ),
    mainPanel(
        tabPanel("test_names", DT::dataTableOutput("table1")),
        tabPanel("test_subtests", DT::dataTableOutput("table2"))
      )
      )
    ),
  server = function(input, output) {

    output$table1 <- DT::renderDataTable(
      tests |>
        dplyr::select(Test:Abbreviation) |>
        DT::datatable(selection = 'single', options=list(scrollX=TRUE))
        )

    output$table2 <- DT::renderDataTable(
      tests |>
        dplyr::select(-Abbreviation) |>
        DT::datatable(selection = 'single', options=list(scrollX=TRUE))
        )

    output$report <- downloadHandler(
      # For PDF output, change this to "report.pdf"
      # filename = "report.docx",
      # content = function(file) {
        # Copy the report file to a temporary directory before processing it, in
        # case we don't have write permissions to the current working dir (which
        # can happen when deployed).
       #  tempReport <- file.path(tempdir(), "report.qmd")
       #  file.copy("report.qmd", tempReport, overwrite = TRUE)

        # Set up parameters to pass to Rmd document
       # params <- 

        # Knit the document, passing in the `params` list, and eval it in a
        # child of the global environment (this isolates the code in the document
        # from the code in this app).
        quarto::quarto_render(
          "index.qmd",
          execute_params = list(
        patient_name = input$patient_name,
        dob = input$dob,
        city = input$city,
        state = input$state,
        interview_date = input$interview_date,
        testing_date = input$testing_date,
        examiner = input$examiner,
        examiner_title = input$examiner_title,
        examiner_license = input$examiner_license,
        examiner2_tf = input$examiner2_tf,
        examiner2 = input$examiner2,
        examiner2_title = input$examiner2_title,
        examiner2_license = input$examiner2_license,
        examiner3_tf = input$examiner3_tf,
        examiner3 = input$examiner3,
        examiner3_title = input$examiner3_title,
        examiner3_license = input$examiner3_license,
        mr_ms = input$mr_ms,
        male_female = input$male_female,
        his_her_their = input$his_her_their,
        he_she_they = input$he_she_they,
        patient_age = input$patient_age,
        handed = input$handed,
        marital_status = input$marital_status,
        race_ethnicity = input$race_ethnicity,
        bilingual = input$bilingual,
        years_of_ed = input$years_of_ed,
        referred = input$referred,
        referring_dr = input$referring_dr,
        past_diagnosis_tf = input$past_diagnosis_tf,
        past_diagnosis = input$past_diagnosis,
        past_dr_diagnosing = input$past_dr_diagnosing,
        age_of_diagnosis = input$age_of_diagnosis,
        time_of_symptom_concern = input$time_of_symptom_concern,
        major_medical_issues = input$major_medical_issues,
        diagnosis_symptoms = input$diagnosis_symptoms,
        current_medications = input$current_medications,
        past_medications = input$past_medications,
        raw_topf = input$raw_topf,
        standard_topf = input$standard_topf,
        percentile_topf = input$percentile_topf,
        score_cvlt_ii_fc = input$score_cvlt_ii_fc,
        total_cvlt_ii_fc = input$total_cvlt_ii_fc,
        score_rds = input$score_rds,
        tomm_trial_1 = input$tomm_trial_1,
        tomm_trial_2 = input$tomm_trial_2,
        raw_similarities = input$raw_similarities,
        acss_similarities = input$acss_similarities,
        percentile_similarities = input$percentile_similarities,
        raw_information = input$raw_information,
        acss_information = input$acss_information,
        percentile_information = input$percentile_information,
        raw_vocab = input$raw_vocab,
        acss_vocab = input$acss_vocab,
        percentile_vocab = input$percentile_vocab,
        raw_block_design = input$raw_block_design,
        acss_block_design = input$acss_block_design,
        percentile_block_design = input$percentile_block_design,
        raw_matrix_reason = input$raw_matrix_reason,
        acss_matrix_reason = input$acss_matrix_reason,
        percentile_matrix_reason = input$percentile_matrix_reason,
        raw_visual_puzzle = input$raw_visual_puzzle,
        acss_visual_puzzle = input$acss_visual_puzzle,
        percentile_visual_puzzle = input$percentile_visual_puzzle,
        raw_digit_span = input$raw_digit_span,
        acss_digit_span = input$acss_digit_span,
        percentile_digit_span = input$percentile_digit_span,
        raw_arithmetic = input$raw_arithmetic,
        acss_arithmetic = input$acss_arithmetic,
        percentile_arithmetic = input$percentile_arithmetic,
        raw_symbol_s = input$raw_symbol_s,
        acss_symbol_s = input$acss_symbol_s,
        percentile_symbol_s = input$percentile_symbol_s,
        raw_coding = input$raw_coding,
        acss_coding = input$acss_coding,
        percentile_coding = input$percentile_coding,
        raw_wais_vcl = input$raw_wais_vcl,
        standard_wais_vcl = input$standard_wais_vcl,
        percentile_wais_vcl = input$percentile_wais_vcl,
        raw_wais_pri = input$raw_wais_pri,
        standard_wais_pri = input$standard_wais_pri,
        percentile_wais_pri = input$percentile_wais_pri,
        raw_wais_gai = input$raw_wais_gai,
        standard_wais_gai = input$standard_wais_gai,
        percentile_wais_gai = input$percentile_wais_gai,
        raw_wais_wmi = input$raw_wais_wmi,
        standard_wais_wmi = input$standard_wais_wmi,
        percentile_wais_wmi = input$percentile_wais_wmi,
        raw_wais_psi = input$raw_wais_psi,
        standard_wais_psi = input$standard_wais_psi,
        percentile_wais_psi = input$percentile_wais_psi,
        raw_wais_fsiq = input$raw_wais_fsiq,
        standard_wais_fsiq = input$standard_wais_fsiq,
        percentile_fsiq = input$percentile_fsiq,
        raw_wais_ds = input$raw_wais_ds,
        acss_wais_ds = input$acss_wais_ds,
        percentile_wais_ds = input$percentile_wais_ds,
        raw_ds_fwd = input$raw_ds_fwd,
        acss_ds_fwd = input$acss_ds_fwd,
        percentile_ds_fwd = input$percentile_ds_fwd,
        raw_ds_bwd = input$raw_ds_bwd,
        acss_ds_bwd = input$acss_ds_bwd,
        percentile_ds_bwd = input$percentile_ds_bwd,
        raw_ds_seq = input$raw_ds_seq,
        acss_ds_seq = input$acss_ds_seq,
        percentile_ds_seq = input$percentile_ds_seq,
        longest_fwd = input$longest_fwd,
        longest_bwd = input$longest_bwd,
        longest_seq = input$longest_seq,
        t_cpt3_d = input$t_cpt3_d,
        rating_cpt3_d = input$rating_cpt3_d,
        t_cpt3_omissions = input$t_cpt3_omissions,
        rating_cpt3_omissions = input$rating_cpt3_omissions,
        t_cpt3_commissions = input$t_cpt3_commissions,
        rating_cpt3_commissions = input$rating_cpt3_commissions,
        t_cpt3_perseverations = input$t_cpt3_perseverations,
        rating_cpt3_perseverations = input$rating_cpt3_perseverations,
        raw_wais_ss = input$raw_wais_ss,
        acss_wais_ss = input$acss_wais_ss,
        percentile_wais_ss = input$percentile_wais_ss,
        raw_wais_co = input$raw_wais_co,
        acss_wais_co = input$acss_wais_co,
        percentile_wais_co = input$percentile_wais_co,
        raw_stroop_word = input$raw_stroop_word,
        t_stroop_word = input$t_stroop_word,
        percentile_stroop_word = input$percentile_stroop_word,
        error_stroop_word = input$error_stroop_word,
        raw_stroop_color = input$raw_stroop_color,
        t_stroop_color = input$t_stroop_color,
        percentile_stroop_color = input$percentile_stroop_color,
        error_stroop_color = input$error_stroop_color,
        raw_trails_a = input$raw_trails_a,
        z_trails_a = input$z_trails_a,
        percentile_trails_a = input$percentile_trails_a,
        error_trails_a = input$error_trails_a,
        raw_hrt = input$raw_hrt,
        t_hrt = input$t_hrt,
        rating_hrt = input$rating_hrt,
        raw_hrt_sd = input$raw_hrt_sd,
        t_hrt_sd = input$t_hrt_sd,
        rating_hrt_sd = input$rating_hrt_sd,
        raw_variability = input$raw_variability,
        t_variability = input$t_variability,
        rating_variability = input$rating_variability,
        raw_hrt_block_change = input$raw_hrt_block_change,
        t_hrt_block_change = input$t_hrt_block_change,
        rating_hrt_block_change = input$rating_hrt_block_change,
        raw_hrt_isi_change = input$raw_hrt_isi_change,
        t_hrt_isi_change = input$t_hrt_isi_change,
        rating_hrt_isi_change = input$rating_hrt_isi_change,
        raw_wcst_categ = input$raw_wcst_categ,
        percentile_wcst_categ = input$percentile_wcst_categ,
        raw_wcst_p_errors = input$raw_wcst_p_errors,
        percentile_wcst_p_errors = input$percentile_wcst_p_errors,
        raw_wcst_clr = input$raw_wcst_clr,
        percentile_wcst_clr = input$percentile_wcst_clr,
        raw_wcst_fms = input$raw_wcst_fms,
        percentile_wcst_fms = input$percentile_wcst_fms,
        raw_wais_si = input$raw_wais_si,
        acss_wais_si = input$acss_wais_si,
        percentile_wais_si = input$percentile_wais_si,
        raw_wais_mr = input$raw_wais_mr,
        acss_wais_mr = input$acss_wais_mr,
        percentile_wais_mr = input$percentile_wais_mr,
        raw_trails_b = input$raw_trails_b,
        z_trails_b = input$z_trails_b,
        percentile_trails_b = input$percentile_trails_b,
        raw_stroop_cw = input$raw_stroop_cw,
        t_stroop_cw = input$t_stroop_cw,
        percentile_stroop_cw = input$percentile_stroop_cw,
        raw_fas = input$raw_fas,
        z_fas = input$z_fas,
        percentile_fas = input$percentile_fas,
        raw_fas_lang = input$raw_fas_lang,
        z_fas_lang = input$z_fas_lang,
        percentile_fas_lang = input$percentile_fas_lang,
        raw_animals = input$raw_animals,
        z_animals = input$z_animals,
        percentile_animals = input$percentile_animals,
        raw_wais_vc = input$raw_wais_vc,
        z_wais_vc = input$z_wais_vc,
        percentile_wais_vc = input$percentile_wais_vc,
        raw_wais_bd = input$raw_wais_bd,
        acss_wais_bd = input$acss_wais_bd,
        percentile_wais_bd = input$percentile_wais_bd,
        raw_wais_vp = input$raw_wais_vp,
        acss_wais_vp = input$acss_wais_vp,
        percentile_wais_vp = input$percentile_wais_vp,
        raw_rcft_copy = input$raw_rcft_copy,
        acss_rcft_copy = input$acss_rcft_copy,
        percentile_rcft_copy = input$percentile_rcft_copy,
        raw_cvlt_3 = input$raw_cvlt_3,
        acss_cvlt_3 = input$acss_cvlt_3,
        percentile_cvlt_3 = input$percentile_cvlt_3,
        raw_trials = input$raw_trials,
        t_trials = input$t_trials,
        percentile_trials = input$percentile_trials,
        raw_list_b = input$raw_list_b,
        acss_list_b = input$acss_list_b,
        percentile_list_b = input$percentile_list_b,
        raw_sd_free = input$raw_sd_free,
        acss_sd_free = input$acss_sd_free,
        percentile_sd_free = input$percentile_sd_free,
        raw_sd_cued = input$raw_sd_cued,
        acss_sd_cued = input$acss_sd_cued,
        percentile_sd_cued = input$percentile_sd_cued,
        raw_ld_free = input$raw_ld_free,
        acss_ld_free = input$acss_ld_free,
        percentile_ld_free = input$percentile_ld_free,
        raw_ld_cued = input$raw_ld_cued,
        acss_ld_cued = input$acss_ld_cued,
        percentile_ld_cued = input$percentile_ld_cued,
        raw_repetitions = input$raw_repetitions,
        acss_repetitions = input$acss_repetitions,
        percentile_repetitions = input$percentile_repetitions,
        raw_intrusions = input$raw_intrusions,
        acss_intrusions = input$acss_intrusions,
        percentile_intrusions = input$percentile_intrusions,
        raw_recog_hits = input$raw_recog_hits,
        acss_recog_hits = input$acss_recog_hits,
        percentile_recog_hits = input$percentile_recog_hits,
        raw_false_positives = input$raw_false_positives,
        acss_false_positives = input$acss_false_positives,
        percentile_false_positives = input$percentile_false_positives,
        raw_ld_recog_accuracy = input$raw_ld_recog_accuracy,
        acss_ld_recog_accuracy = input$acss_ld_recog_accuracy,
        percentile_ld_recog_accuracy = input$percentile_ld_recog_accuracy,
        raw_wms_iv = input$raw_wms_iv,
        acss_wms_iv = input$acss_wms_iv,
        percentile_wms_iv = input$percentile_wms_iv,
        raw_lm_i = input$raw_lm_i,
        acss_lm_i = input$acss_lm_i,
        percentile_lm_i = input$percentile_lm_i,
        raw_lm_ii = input$raw_lm_ii,
        acss_lm_ii = input$acss_lm_ii,
        percentile_lm_ii = input$percentile_lm_ii,
        raw_recognition = input$raw_recognition,
        acss_recognition = input$acss_recognition,
        percentile_recognition = input$percentile_recognition,
        raw_rcft_3 = input$raw_rcft_3,
        t_rcft_3 = input$t_rcft_3,
        percentile_rcft_3 = input$percentile_rcft_3,
        raw_rcft_30 = input$raw_rcft_30,
        t_rcft_30 = input$t_rcft_30,
        percentile_rcft_30 = input$percentile_rcft_30,
        raw_rcft_total_recog = input$raw_rcft_total_recog,
        t_rcft_total_recog = input$t_rcft_total_recog,
        percentile_rcft_total_recog = input$percentile_rcft_total_recog,
        score_bdi_ii = input$score_bdi_ii,
        score_bai = input$score_bai,
        t_inattention = input$t_inattention,
        t_hyperactivity = input$t_hyperactivity,
        t_impulsivity = input$t_impulsivity,
        t_self_concept = input$t_self_concept,
        t_dsm_inattentive = input$t_dsm_inattentive,
        t_dsm_hyperactive = input$t_dsm_hyperactive,
        t_dsm_adhd_total = input$t_dsm_adhd_total,
        t_adhd_index = input$t_adhd_index,
        level_depression = input$level_depression,
        level_anxiety = input$level_anxiety,
        beginning_symptoms = input$beginning_symptoms,
        hs_college_symptoms = input$hs_college_symptoms,
        occupational_symptoms = input$occupational_symptoms,
        current_mood = input$current_mood,
        current_sleep = input$current_sleep,
        motor_sensory_functioning = input$motor_sensory_functioning,
        current = input$current,
        medical_history = input$medical_history,
        family_history = input$family_history,
        psychiatric_history = input$psychiatric_history,
        substance_use_history = input$substance_use_history,
        developmental_ed_social_occupation = input$developmental_ed_social_occupation,
        behavioral_observations = input$behavioral_observations,
        administered_tests = input$administered_tests,
        intellectual_functioning_results = input$intellectual_functioning_results,
        attention_concentration_results = input$attention_concentration_results,
        processing_speed_results = input$processing_speed_results,
        executive_function_results = input$executive_function_results,
        language_skill_results = input$language_skill_results,
        visual_spatial_results = input$visual_spatial_results,
        memory_results = input$memory_results,
        mood_personality_results = input$mood_personality_results,
        summary_impressions = input$summary_impressions,
        academic_accommodations = input$academic_accommodations
          )
          # envir = new.env(parent = globalenv())
    )
      # }
    )
  }
)
