library(shiny)

shinyApp(
  ui = fluidPage(
    titlePanel("Template Creation for Neuropsychology Patient Reports"),

    textInput("examiner", "Examiner's Name"),
    selectInput("examiner2_tf", "Is there a second examiner", choices = c(TRUE, FALSE)),
    textInput("examiner2", "Second Examiner's Name"),
    selectInput("examiner3_tf", "Is there a third examiner", choices = c(TRUE, FALSE)),
    textInput("examiner3", "Third Examiner's Name"),
    textInput("patient_name", "Patient's Name"),
    textInput("eval_date", "Evaluation Date (e.g., MM/DD/YYYY)"),
    selectInput("second_test", "Is this a re-evaluation", choices = c(TRUE, FALSE)),
    textInput("past_eval_date", "Previous evaluation date (e.g., MM/DD/YYYY)"),
    textInput("report_date", "Report Date/Today (e.g., MM/DD/YYYY)"),
    selectInput("mr_ms", "Name prefix", choices = c("Mr.", "Ms", "Mrs.", "Dr.")),
    selectInput("male_female", "Male/Female/Non-binary", choices = c("male", "female", "non-binary")),
    selectInput("his_her_their", "His/Her/Their", choices = c("his", "her", "their")),
    selectInput("he_she_they", "He/She/They", choices = c("he", "she", "they")),
    textInput("patient_age", "Patient's Age"),
    textInput("dob", "Patient's Date of Birth"),
    selectInput("handed", "Right or left-handed", choices = c("right", "left")),
    selectInput("marital_status", "Patient's marital status", choices = c("single", "married", "widowed", "divorced", "separated")),
    textInput("race_ethnicity", "Patient's Race/Ethnicity"),
    selectInput("bilingual", "Is the patient bilingual?", choices = c("Yes", "No")),
    textInput("years_of_ed", "Years of Education"),
    textInput("referring_dr", "Referring Doctor's Name"),
    selectInput("accompany", "Is someone accompanying patient", choices = c(TRUE, FALSE)),
    textInput("accompany_relationship", "Relationship to patient"),
    textInput("accompany_name", "Accompanying person's name"),
    textInput("major_medical_issue1", "Name of first major medical issue"),
    textInput("major_medical_issue2", "Name of second major medical issue"),
    textInput("major_medical_issue3", "Name of third major medical issue"),
    textInput("major_medical_issue4", "Name of fourth major medical issue"),
    textInput("major_medical_issue5", "Name of fifth major medical issue"),
    selectInput("medical_decline_status", "Level of medical decline status", choices = c("progressive", "stable", "longstanding", "stepwise", "acute")),
    downloadButton("report", "Generate report")
  ),
  server = function(input, output){
    output$result <- renderUI({
      intput$examiner
      # intput$examiner2_tf,
      # intput$examiner2,
      # intput$examiner3_tf,
      # intput$examiner3,
      # intput$patient_name,
      # intput$eval_date,
      # intput$second_test,
      # intput$past_eval_date,
      # intput$report_date,
      # intput$mr_ms,
      # intput$male_female,
      # intput$his_her_their,
      # intput$he_she_they,
      # intput$patient_age,
      # intput$dob,
      # intput$handed,
      # intput$marital_status,
      # intput$race_ethnicity,
      # intput$bilingual,
      # input$years_of_ed,
      # input$referring_dr,
      # input$accompany,
      # input$accompany_relationship,
      # input$accompany_name,
      # input$major_medical_issue1,
      # input$major_medical_issue2,
      # input$major_medical_issue3,
      # input$major_medical_issue4,
      # input$major_medical_issue5,
      # iniput$medical_decline_status,
      # input$report
    })
  }
)
